version: '3.8'

services:
  vsgan_tensorrt:
    stdin_open: true 
    tty: true        
    image: krntl/videoupscale:24_10_18 
    volumes:
      # Replace /root/inputs with the path to your inputs folder
      - /root/inputs:/workspace/tensorrt/inputs
      # Replace /root/outputs with the path to your inputs folder
      - /root/outputs:/workspace/tensorrt/outputs
      # Replace /root/engine with the path to your inputs folder
      - /root/engine:/workspace/tensorrt/app/engine
    privileged: true
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /workspace/tensorrt
